GET https://localhost:7168/api/public/test
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJZCI6IjEiLCJlbWFpbCI6InVzZXJAYXBwLmxvYyIsInN1YiI6InVzZXJAYXBwLmxvYyIsImp0aSI6IjcyOWY0MzJjLThiODctNDAwZC04ZjI3LWE3NmNiNTUzNDkwZSIsIm5iZiI6MTY2NTk5Mjk3NCwiZXhwIjoxNjY2NTk3Nzc0LCJpYXQiOjE2NjU5OTI5NzR9.VCUVi0mO_9pcg9KFvt4rVLfYri5OVcJ47IsKF9_twps
